// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mburtless/ns1-go/models"
)

// NewCreateZoneParams creates a new CreateZoneParams object
// with the default values initialized.
func NewCreateZoneParams() *CreateZoneParams {
	var ()
	return &CreateZoneParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateZoneParamsWithTimeout creates a new CreateZoneParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateZoneParamsWithTimeout(timeout time.Duration) *CreateZoneParams {
	var ()
	return &CreateZoneParams{

		timeout: timeout,
	}
}

// NewCreateZoneParamsWithContext creates a new CreateZoneParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateZoneParamsWithContext(ctx context.Context) *CreateZoneParams {
	var ()
	return &CreateZoneParams{

		Context: ctx,
	}
}

// NewCreateZoneParamsWithHTTPClient creates a new CreateZoneParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateZoneParamsWithHTTPClient(client *http.Client) *CreateZoneParams {
	var ()
	return &CreateZoneParams{
		HTTPClient: client,
	}
}

/*CreateZoneParams contains all the parameters to send to the API endpoint
for the create zone operation typically these are written to a http.Request
*/
type CreateZoneParams struct {

	/*Body
	  The zone to create

	*/
	Body *models.ZoneRequest
	/*Zone
	  The name of the zone to retrieve

	*/
	Zone string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create zone params
func (o *CreateZoneParams) WithTimeout(timeout time.Duration) *CreateZoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create zone params
func (o *CreateZoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create zone params
func (o *CreateZoneParams) WithContext(ctx context.Context) *CreateZoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create zone params
func (o *CreateZoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create zone params
func (o *CreateZoneParams) WithHTTPClient(client *http.Client) *CreateZoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create zone params
func (o *CreateZoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create zone params
func (o *CreateZoneParams) WithBody(body *models.ZoneRequest) *CreateZoneParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create zone params
func (o *CreateZoneParams) SetBody(body *models.ZoneRequest) {
	o.Body = body
}

// WithZone adds the zone to the create zone params
func (o *CreateZoneParams) WithZone(zone string) *CreateZoneParams {
	o.SetZone(zone)
	return o
}

// SetZone adds the zone to the create zone params
func (o *CreateZoneParams) SetZone(zone string) {
	o.Zone = zone
}

// WriteToRequest writes these params to a swagger request
func (o *CreateZoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param zone
	if err := r.SetPathParam("zone", o.Zone); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
