// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetZoneParams creates a new GetZoneParams object
// with the default values initialized.
func NewGetZoneParams() *GetZoneParams {
	var ()
	return &GetZoneParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetZoneParamsWithTimeout creates a new GetZoneParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetZoneParamsWithTimeout(timeout time.Duration) *GetZoneParams {
	var ()
	return &GetZoneParams{

		timeout: timeout,
	}
}

// NewGetZoneParamsWithContext creates a new GetZoneParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetZoneParamsWithContext(ctx context.Context) *GetZoneParams {
	var ()
	return &GetZoneParams{

		Context: ctx,
	}
}

// NewGetZoneParamsWithHTTPClient creates a new GetZoneParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetZoneParamsWithHTTPClient(client *http.Client) *GetZoneParams {
	var ()
	return &GetZoneParams{
		HTTPClient: client,
	}
}

/*GetZoneParams contains all the parameters to send to the API endpoint
for the get zone operation typically these are written to a http.Request
*/
type GetZoneParams struct {

	/*Zone
	  The name of the zone to retrieve

	*/
	Zone string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get zone params
func (o *GetZoneParams) WithTimeout(timeout time.Duration) *GetZoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get zone params
func (o *GetZoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get zone params
func (o *GetZoneParams) WithContext(ctx context.Context) *GetZoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get zone params
func (o *GetZoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get zone params
func (o *GetZoneParams) WithHTTPClient(client *http.Client) *GetZoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get zone params
func (o *GetZoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithZone adds the zone to the get zone params
func (o *GetZoneParams) WithZone(zone string) *GetZoneParams {
	o.SetZone(zone)
	return o
}

// SetZone adds the zone to the get zone params
func (o *GetZoneParams) SetZone(zone string) {
	o.Zone = zone
}

// WriteToRequest writes these params to a swagger request
func (o *GetZoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param zone
	if err := r.SetPathParam("zone", o.Zone); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
