// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mburtless/ns1-go/models"
)

// GetZoneReader is a Reader for the GetZone structure.
type GetZoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetZoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetZoneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetZoneBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetZoneNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetZoneOK creates a GetZoneOK with default headers values
func NewGetZoneOK() *GetZoneOK {
	return &GetZoneOK{}
}

/*GetZoneOK handles this case with default header values.

A single active zone
*/
type GetZoneOK struct {
	Payload *models.Zone
}

func (o *GetZoneOK) Error() string {
	return fmt.Sprintf("[GET /zones/{zone}][%d] getZoneOK  %+v", 200, o.Payload)
}

func (o *GetZoneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Zone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZoneBadRequest creates a GetZoneBadRequest with default headers values
func NewGetZoneBadRequest() *GetZoneBadRequest {
	return &GetZoneBadRequest{}
}

/*GetZoneBadRequest handles this case with default header values.

Bad Request
*/
type GetZoneBadRequest struct {
	Payload *models.Error
}

func (o *GetZoneBadRequest) Error() string {
	return fmt.Sprintf("[GET /zones/{zone}][%d] getZoneBadRequest  %+v", 400, o.Payload)
}

func (o *GetZoneBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZoneNotFound creates a GetZoneNotFound with default headers values
func NewGetZoneNotFound() *GetZoneNotFound {
	return &GetZoneNotFound{}
}

/*GetZoneNotFound handles this case with default header values.

Zone not found
*/
type GetZoneNotFound struct {
	Payload *models.Error
}

func (o *GetZoneNotFound) Error() string {
	return fmt.Sprintf("[GET /zones/{zone}][%d] getZoneNotFound  %+v", 404, o.Payload)
}

func (o *GetZoneNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
