// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mburtless/ns1-go-v3/models"
)

// ZonesByZonePostReader is a Reader for the ZonesByZonePost structure.
type ZonesByZonePostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ZonesByZonePostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewZonesByZonePostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewZonesByZonePostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewZonesByZonePostOK creates a ZonesByZonePostOK with default headers values
func NewZonesByZonePostOK() *ZonesByZonePostOK {
	return &ZonesByZonePostOK{}
}

/*ZonesByZonePostOK handles this case with default header values.

A single active zone
*/
type ZonesByZonePostOK struct {
	Payload *models.Zone
}

func (o *ZonesByZonePostOK) Error() string {
	return fmt.Sprintf("[POST /zones/{zone}][%d] zonesByZonePostOK  %+v", 200, o.Payload)
}

func (o *ZonesByZonePostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Zone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewZonesByZonePostBadRequest creates a ZonesByZonePostBadRequest with default headers values
func NewZonesByZonePostBadRequest() *ZonesByZonePostBadRequest {
	return &ZonesByZonePostBadRequest{}
}

/*ZonesByZonePostBadRequest handles this case with default header values.

Bad Request
*/
type ZonesByZonePostBadRequest struct {
	Payload interface{}
}

func (o *ZonesByZonePostBadRequest) Error() string {
	return fmt.Sprintf("[POST /zones/{zone}][%d] zonesByZonePostBadRequest  %+v", 400, o.Payload)
}

func (o *ZonesByZonePostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
