// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mburtless/ns1-go-v3/models"
)

// NewZonesByZonePostParams creates a new ZonesByZonePostParams object
// with the default values initialized.
func NewZonesByZonePostParams() *ZonesByZonePostParams {
	var ()
	return &ZonesByZonePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewZonesByZonePostParamsWithTimeout creates a new ZonesByZonePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewZonesByZonePostParamsWithTimeout(timeout time.Duration) *ZonesByZonePostParams {
	var ()
	return &ZonesByZonePostParams{

		timeout: timeout,
	}
}

// NewZonesByZonePostParamsWithContext creates a new ZonesByZonePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewZonesByZonePostParamsWithContext(ctx context.Context) *ZonesByZonePostParams {
	var ()
	return &ZonesByZonePostParams{

		Context: ctx,
	}
}

// NewZonesByZonePostParamsWithHTTPClient creates a new ZonesByZonePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewZonesByZonePostParamsWithHTTPClient(client *http.Client) *ZonesByZonePostParams {
	var ()
	return &ZonesByZonePostParams{
		HTTPClient: client,
	}
}

/*ZonesByZonePostParams contains all the parameters to send to the API endpoint
for the zones by zone post operation typically these are written to a http.Request
*/
type ZonesByZonePostParams struct {

	/*Body
	  The zone to create

	*/
	Body *models.ZoneRequest
	/*Zone
	  The name of the zone to retrieve

	*/
	Zone string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the zones by zone post params
func (o *ZonesByZonePostParams) WithTimeout(timeout time.Duration) *ZonesByZonePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the zones by zone post params
func (o *ZonesByZonePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the zones by zone post params
func (o *ZonesByZonePostParams) WithContext(ctx context.Context) *ZonesByZonePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the zones by zone post params
func (o *ZonesByZonePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the zones by zone post params
func (o *ZonesByZonePostParams) WithHTTPClient(client *http.Client) *ZonesByZonePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the zones by zone post params
func (o *ZonesByZonePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the zones by zone post params
func (o *ZonesByZonePostParams) WithBody(body *models.ZoneRequest) *ZonesByZonePostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the zones by zone post params
func (o *ZonesByZonePostParams) SetBody(body *models.ZoneRequest) {
	o.Body = body
}

// WithZone adds the zone to the zones by zone post params
func (o *ZonesByZonePostParams) WithZone(zone string) *ZonesByZonePostParams {
	o.SetZone(zone)
	return o
}

// SetZone adds the zone to the zones by zone post params
func (o *ZonesByZonePostParams) SetZone(zone string) {
	o.Zone = zone
}

// WriteToRequest writes these params to a swagger request
func (o *ZonesByZonePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param zone
	if err := r.SetPathParam("zone", o.Zone); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
