// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewZonesGetParams creates a new ZonesGetParams object
// with the default values initialized.
func NewZonesGetParams() *ZonesGetParams {

	return &ZonesGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewZonesGetParamsWithTimeout creates a new ZonesGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewZonesGetParamsWithTimeout(timeout time.Duration) *ZonesGetParams {

	return &ZonesGetParams{

		timeout: timeout,
	}
}

// NewZonesGetParamsWithContext creates a new ZonesGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewZonesGetParamsWithContext(ctx context.Context) *ZonesGetParams {

	return &ZonesGetParams{

		Context: ctx,
	}
}

// NewZonesGetParamsWithHTTPClient creates a new ZonesGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewZonesGetParamsWithHTTPClient(client *http.Client) *ZonesGetParams {

	return &ZonesGetParams{
		HTTPClient: client,
	}
}

/*ZonesGetParams contains all the parameters to send to the API endpoint
for the zones get operation typically these are written to a http.Request
*/
type ZonesGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the zones get params
func (o *ZonesGetParams) WithTimeout(timeout time.Duration) *ZonesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the zones get params
func (o *ZonesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the zones get params
func (o *ZonesGetParams) WithContext(ctx context.Context) *ZonesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the zones get params
func (o *ZonesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the zones get params
func (o *ZonesGetParams) WithHTTPClient(client *http.Client) *ZonesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the zones get params
func (o *ZonesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ZonesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
