// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewZonesByZoneGetParams creates a new ZonesByZoneGetParams object
// with the default values initialized.
func NewZonesByZoneGetParams() *ZonesByZoneGetParams {
	var ()
	return &ZonesByZoneGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewZonesByZoneGetParamsWithTimeout creates a new ZonesByZoneGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewZonesByZoneGetParamsWithTimeout(timeout time.Duration) *ZonesByZoneGetParams {
	var ()
	return &ZonesByZoneGetParams{

		timeout: timeout,
	}
}

// NewZonesByZoneGetParamsWithContext creates a new ZonesByZoneGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewZonesByZoneGetParamsWithContext(ctx context.Context) *ZonesByZoneGetParams {
	var ()
	return &ZonesByZoneGetParams{

		Context: ctx,
	}
}

// NewZonesByZoneGetParamsWithHTTPClient creates a new ZonesByZoneGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewZonesByZoneGetParamsWithHTTPClient(client *http.Client) *ZonesByZoneGetParams {
	var ()
	return &ZonesByZoneGetParams{
		HTTPClient: client,
	}
}

/*ZonesByZoneGetParams contains all the parameters to send to the API endpoint
for the zones by zone get operation typically these are written to a http.Request
*/
type ZonesByZoneGetParams struct {

	/*Zone
	  The name of the zone to retrieve

	*/
	Zone string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the zones by zone get params
func (o *ZonesByZoneGetParams) WithTimeout(timeout time.Duration) *ZonesByZoneGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the zones by zone get params
func (o *ZonesByZoneGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the zones by zone get params
func (o *ZonesByZoneGetParams) WithContext(ctx context.Context) *ZonesByZoneGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the zones by zone get params
func (o *ZonesByZoneGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the zones by zone get params
func (o *ZonesByZoneGetParams) WithHTTPClient(client *http.Client) *ZonesByZoneGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the zones by zone get params
func (o *ZonesByZoneGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithZone adds the zone to the zones by zone get params
func (o *ZonesByZoneGetParams) WithZone(zone string) *ZonesByZoneGetParams {
	o.SetZone(zone)
	return o
}

// SetZone adds the zone to the zones by zone get params
func (o *ZonesByZoneGetParams) SetZone(zone string) {
	o.Zone = zone
}

// WriteToRequest writes these params to a swagger request
func (o *ZonesByZoneGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param zone
	if err := r.SetPathParam("zone", o.Zone); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
