// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ZoneRequest zone request
// swagger:model ZoneRequest
type ZoneRequest struct {

	// dns servers
	DNSServers []string `json:"dns_servers"`

	// expiry
	Expiry int64 `json:"expiry,omitempty"`

	// hostmaster
	Hostmaster string `json:"hostmaster,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// meta
	Meta *Metadata `json:"meta,omitempty"`

	// network pools
	NetworkPools []string `json:"network_pools"`

	// networks
	Networks []int64 `json:"networks"`

	// nx ttl
	NxTTL int64 `json:"nx_ttl,omitempty"`

	// primary
	Primary *ZoneRequestPrimary `json:"primary,omitempty"`

	// records
	Records []*ZoneRequestRecordsItems0 `json:"records"`

	// refresh
	Refresh int64 `json:"refresh,omitempty"`

	// retry
	Retry int64 `json:"retry,omitempty"`

	// ttl
	TTL int64 `json:"ttl,omitempty"`

	// zone
	Zone string `json:"zone,omitempty"`
}

// Validate validates this zone request
func (m *ZoneRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrimary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecords(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ZoneRequest) validateMeta(formats strfmt.Registry) error {

	if swag.IsZero(m.Meta) { // not required
		return nil
	}

	if m.Meta != nil {
		if err := m.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("meta")
			}
			return err
		}
	}

	return nil
}

func (m *ZoneRequest) validatePrimary(formats strfmt.Registry) error {

	if swag.IsZero(m.Primary) { // not required
		return nil
	}

	if m.Primary != nil {
		if err := m.Primary.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primary")
			}
			return err
		}
	}

	return nil
}

func (m *ZoneRequest) validateRecords(formats strfmt.Registry) error {

	if swag.IsZero(m.Records) { // not required
		return nil
	}

	for i := 0; i < len(m.Records); i++ {
		if swag.IsZero(m.Records[i]) { // not required
			continue
		}

		if m.Records[i] != nil {
			if err := m.Records[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("records" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ZoneRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZoneRequest) UnmarshalBinary(b []byte) error {
	var res ZoneRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ZoneRequestPrimary zone request primary
// swagger:model ZoneRequestPrimary
type ZoneRequestPrimary struct {

	// enabled
	// Required: true
	Enabled *bool `json:"enabled"`

	// secondaries
	// Required: true
	Secondaries []*Secondaries `json:"secondaries"`
}

// Validate validates this zone request primary
func (m *ZoneRequestPrimary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecondaries(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ZoneRequestPrimary) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("primary"+"."+"enabled", "body", m.Enabled); err != nil {
		return err
	}

	return nil
}

func (m *ZoneRequestPrimary) validateSecondaries(formats strfmt.Registry) error {

	if err := validate.Required("primary"+"."+"secondaries", "body", m.Secondaries); err != nil {
		return err
	}

	for i := 0; i < len(m.Secondaries); i++ {
		if swag.IsZero(m.Secondaries[i]) { // not required
			continue
		}

		if m.Secondaries[i] != nil {
			if err := m.Secondaries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("primary" + "." + "secondaries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ZoneRequestPrimary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZoneRequestPrimary) UnmarshalBinary(b []byte) error {
	var res ZoneRequestPrimary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ZoneRequestRecordsItems0 zone request records items0
// swagger:model ZoneRequestRecordsItems0
type ZoneRequestRecordsItems0 struct {

	// domain
	Domain string `json:"domain,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// short answers
	ShortAnswers []string `json:"short_answers"`

	// tier
	Tier int64 `json:"tier,omitempty"`

	// ttl
	TTL int64 `json:"ttl,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this zone request records items0
func (m *ZoneRequestRecordsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ZoneRequestRecordsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZoneRequestRecordsItems0) UnmarshalBinary(b []byte) error {
	var res ZoneRequestRecordsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
